services:
  - type: web
    name: react-jobs
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        value: "/api"
    routes:
      - type: rewrite
        source: /api/jobs
        destination: /jobs.json
      - type: rewrite
        source: /api/jobs/(.*)
        destination: /jobs.json
      - type: rewrite
        source: /(.*)
        destination: /index.html